name: cucumber_dart
description: A Cucumber for Dart
version: 0.0.1
# repository: https://github.com/christianhujer/cucumber-dart

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
