name: cornichon_dart
description: A BDD-Framework for Dart
version: 0.0.1
# repository: https://github.com/christianhujer/cornichon-dart

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  test: ^1.24.0

dev_dependencies:
  lints: ^4.0.0
